server:
  port: 9007
spring:
  application:
    name: pwr-statistics-service
feign:
  hystrix:
    enabled: true
management:
  context-path: /meta
endpoints:
  cors:
    allowed-methods: '*'
    allowed-origins: '*'
eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_URL}
---
spring:
  profiles: localDev
eureka:
  client:
    enabled: false
pwr-profile-service:
  ribbon:
    listOfServers: power02.corp.hbt.de:9004
---
spring:
  profiles: integration
eureka:
 client:
   enabled: true
---
spring:
  profiles: production
eureka:
 client:
   enabled: true
logging:
  file: /usr/share/power2/statistics/logfile.log